import React from 'react';
import { makeStyles } from '@material-ui/core/styles';
import AppBar from '@material-ui/core/AppBar';
import CssBaseline from '@material-ui/core/CssBaseline';
import Toolbar from '@material-ui/core/Toolbar';
import Typography from '@material-ui/core/Typography';
import IconButton from '@material-ui/core/IconButton';
import Paper from '@material-ui/core/Paper';
import Fab from '@material-ui/core/Fab';
import MenuIcon from '@material-ui/icons/Menu';
import CameraEnhanceIcon from '@material-ui/icons/CameraEnhance';
import PictureAsPdfIcon from '@material-ui/icons/PictureAsPdf';


const messages = [
  {
    id: 1,
    primary: 'Brunch this week?',
    secondary: "I'll be in the neighbourhood this week. Let's grab a bite to eat",
    person: '/static/images/avatar/5.jpg',
  },
  {
    id: 2,
    primary: 'Birthday Gift',
    secondary: `Do you have a suggestion for a good present for John on his work
      anniversary. I am really confused & would love your thoughts on it.`,
    person: '/static/images/avatar/1.jpg',
  },
  {
    id: 3,
    primary: 'Recipe to try',
    secondary: 'I am try out this new BBQ recipe, I think this might be amazing',
    person: '/static/images/avatar/2.jpg',
  },
  {
    id: 4,
    primary: 'Yes!',
    secondary: 'I have the tickets to the ReactConf for this year.',
    person: '/static/images/avatar/3.jpg',
  },
  {
    id: 5,
    primary: "Doctor's Appointment",
    secondary: 'My appointment for the doctor was rescheduled for next Saturday.',
    person: '/static/images/avatar/4.jpg',
  },
  {
    id: 6,
    primary: 'Discussion',
    secondary: `Menus that are generated by the bottom app bar (such as a bottom
      navigation drawer or overflow menu) open as bottom sheets at a higher elevation
      than the bar.`,
    person: '/static/images/avatar/5.jpg',
  },
  {
    id: 7,
    primary: 'Summer BBQ',
    secondary: `Who wants to have a cookout this weekend? I just got some furniture
      for my backyard and would love to fire up the grill.`,
    person: '/static/images/avatar/1.jpg',
  },
];

const useStyles = makeStyles((theme) => ({
  text: {
    padding: theme.spacing(2, 2, 0),
  },
  paper: {
    paddingBottom: 1,
  },
  list: {
    marginBottom: theme.spacing(2),
  },
  subheader: {
    backgroundColor: theme.palette.background.paper,
  },
  appBar: {
    top: 'auto',
    bottom: 0,
    backgroundColor: "black"
  },
  grow: {
    flexGrow: 1,
  }
}));

export default function ApplicationBar({title, visible}) {
  const classes = useStyles();

  return (
    <React.Fragment >
      <CssBaseline />
      { visible ? (
          <Paper square className={classes.paper}>
          <Typography className={classes.text} variant="h5" gutterBottom>
            {title}
          </Typography>
        
        </Paper>
      ) : (<></>) }
    
      <AppBar position="fixed" className={classes.appBar}>
        <Toolbar >
       
          <a class="animate__animated animate__jackInTheBox" style={{
             position: 'absolute',
             zIndex: 1,
             top: -40,
             left: 30,
             right: 0,
             margin: '0'
          }}  target="_blank" href="https://walle-api-madam-birras.herokuapp.com/ar.html">
            <Fab style={{backgroundColor: "#ffd500", width: 80, height:80}} aria-label="add" className={classes.fabButton}>
              <CameraEnhanceIcon style={{fontSize:50}}/>
            </Fab>
          </a>
          <div className={classes.grow} />
          <a class="animate__animated animate__jackInTheBox" href="https://walle-api-madam-birras.herokuapp.com/menu.pdf">
          <IconButton color="inherit">
            <PictureAsPdfIcon style={{fontSize:50, color: 'white'}}/>
          </IconButton>
          </a>
        </Toolbar>
      </AppBar>
    </React.Fragment>
  );
}